title: kahveci group talks
description: All of our presentations can be accessed from this page.



baseurl: "/mytalks" # the subpath of your site, e.g. /blog
url: "https://kahveci.pw" # the base hostname & protocol for your site
permalink: /:title/


compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []
  
  
analytics: UA-129160204-1

color-1: '#e74c3c'
color-2: '##1abc9c'
color-3: '##1abc9c'
color-4: '##1abc9c'
color-5: '##1abc9c'
color-6: '##1abc9c'
color-7: '##1abc9c'
color-8: '##1abc9c'

